siiibo/hisyonosuke

README.md, hisyonosuke/src/app.ts, hisyonosuke/src/birthday-registrator/birthday-registrator.ts, hisyonosuke/src/workflow-customstep/workflow-customstep.ts
Spreadsheetの取得方法を変更するためのPR。
より具体には、activeなスプレッドシートを取得する方法からIDで開く方法に変更。
コンテキスト依存の解消。
=> [fix] change method to open spreadsheet

hisyonosuke/appsscript.json, hisyonosuke/package.json, hisyonosuke/src/app.ts, hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/auth.ts, hisyonosuke/src/attendance-manager/config.ts, hisyonosuke/src/attendance-manager/freee.ts, hisyonosuke/src/attendance-manager/utilities.ts, yarn.lock
freeeの勤怠管理をSlackで行うための機能実装。
https://trello.com/c/Mxl7DFFE
=> [feature] add attendance managagement

hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/freee.ts
https://trello.com/c/Mxl7DFFE/1279-slack%E3%81%AE%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%97%E3%81%A7freee%E3%81%AE%E6%89%93%E5%88%BB で発覚したバグの修正。
=> [fix] 自動入力された休憩打刻情報がリモートメモ追加時に消えてしまうバグの修正

hisyonosuke/src/attendance-manager/attendanceManager.ts
リモートで出勤して途中で出社した場合、リモートメモが書き込まれるべきではないのに書き込まれる仕様になっていた。
（これは意図した挙動で、前回のPRではリリースを優先させた）
上記の仕様は交通費計算に影響を与えてしまう & 毎回エラーが発生してしまうため、リモート→出社の切り替えに対応する。
=> [feature] リモート→出社パターンへの対応

hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/utilities.ts
休日判定処理にバグがあったが、そもそも休日判定処理は無くした方が良さそうだったので修正ではなく削除した。
=> [fix] 休日判定処理の削除

hisyonosuke/src/app.ts
週次之介の以下の機能を秘書之介に移行した。
- アルバイトシフト通知（日次）
- チャンネル作成通知
- 絵文字変更通知
---
毎週水曜のhuddleで[ファシリテーションスキルを持ったボットが欲しい](https://www.notion.so/siiibo/7d2bfb66062c40a295e3c480f19f236e)という話が上がっており、[mebo](https://mebo.work/)というアプリを試すことになった。
この際、週次之介に設定されているイベント購読用エンドポイントを[今まで利用していたGAS製ツールからmebo用のURLに変更した](https://siiibo.slack.com/archives/C0107S3RK24/p1654064345320509)ので、秘書之介で担うことにした。
=> [feature] 週次之介から一部機能を移行

hisyonosuke/src/attendance-manager/attendanceManager.ts
https://github.com/siiibo/hisyonosuke/pull/14 にバグがあるままMergeしてしまったので修正
=> fix: getUserWorkStatusesByMessagesのバグ修正

hisyonosuke/src/app.ts, hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/birthday-registrator/birthday-registrator.ts, hisyonosuke/src/birthday-registrator/modals.ts, hisyonosuke/src/notificator.ts, hisyonosuke/src/workflow-customstep/workflow-customstep.ts, hisyonosuke/tsconfig.json
https://github.com/siiibo/hisyonosuke/pull/14, https://github.com/siiibo/hisyonosuke/pull/15 で追加した `getUpdatedUserWorkStatus` において以下のエラーが発生したため修正を入れる。
`TypeError: Cannot read property 'processedCommands' of undefined at getUpdatedUserWorkStatus`
---
今回は人的要因（書いた型が嘘をついていた）であるが、undefinded error（実行時エラー）の多くはTypeScriptをstrictモードにすることで減らせるので、この際strictモードを利用するように変更する。
=> Change mode strict

attendance-aggregation/src/slack.ts
!message.text なんてないだろうと思って雑にthrow Error書いていた部分でエラー発生していたので修正する。
🔗  https://trello.com/c/0QJwEwoW
=> Fix (attendance-aggregation) : 勤怠集計出力時のエラー解消

hisyonosuke/.eslintrc.json, hisyonosuke/.prittierrc.json, hisyonosuke/package.json, hisyonosuke/src/app.ts, hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/auth.ts, hisyonosuke/src/attendance-manager/config.ts, hisyonosuke/src/attendance-manager/freee.ts, hisyonosuke/src/attendance-manager/utilities.ts, hisyonosuke/src/birthday-registrator/birthday-registrator.ts, hisyonosuke/src/birthday-registrator/modals.ts, hisyonosuke/src/notificator.ts, hisyonosuke/src/workflow-customstep/modals.ts, hisyonosuke/src/workflow-customstep/workflow-customstep.ts, yarn.lock
LinterとFormatterが設定されていなかったので設定する。
=> [hisyonosuke] Chore: LinterとFormatterの設定

.vscode/settings.json
https://github.com/siiibo/hisyonosuke/pull/21 でLinter & Formatterを追加したが、VSCodeの設定を変更していなかったので変更する。
=> Chore: VSCodeのsettings.jsonの追加

hisyonosuke/src/app.ts, hisyonosuke/src/index.ts, hisyonosuke/webpack.config.js
GASで利用する関数の定義のみ行うファイル（index.ts）を新規作成する
---
https://github.com/hi-se/gas-template 含め、最近利用しているスタイルなのでそちらに合わせる
=> [hisyonosuke] Refactor: index.tsにGAS用の関数を集約

hisyonosuke/package.json, hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/freee.schema.ts, hisyonosuke/src/attendance-manager/freee.ts, yarn.lock
freee APIの型を厳密にし、例外処理の改善を行う。
---
- [freee公式のAPI Schema](https://developer.freee.co.jp/reference/hr/reference)からZod Schemaを生成
- https://github.com/astahmer/openapi-zod-client を部分的に利用
- freeeでfetchする際の共通部分を関数化
- 共通ヘッダーやresponseのparseなど
- https://github.com/supermacro/neverthrow を使った例外処理に書き換え
=> [attendance-maanager] Refactor: freee APIの型 & 例外処理の改善

hisyonosuke/src/app.ts, hisyonosuke/src/birthday-registrator/birthday-registrator.ts, hisyonosuke/src/birthday-registrator/modals.ts, hisyonosuke/src/notificator.ts, hisyonosuke/src/workflow-customstep/workflow-customstep.ts
https://github.com/siiibo/hisyonosuke/pull/21 で設定したESLintについて、エラーを解消していない部分があったので解消する
=> [hisyonosuke] Fix: ESLint errorの解消

hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/freee.ts
別アプリでスプレッドシートのonOpen関数を利用する際にScriptProperties取得権限がないというエラーが発生した。 ([Trelloコメント](https://trello.com/c/9P3k440s/7-%E3%82%A2%E3%83%AB%E3%83%90%E3%82%A4%E3%83%88%E3%81%AE%E3%82%B7%E3%83%95%E3%83%88%E5%A4%89%E6%9B%B4%E7%94%A8%E3%83%84%E3%83%BC%E3%83%AB%E3%81%AE%E4%BD%9C%E6%88%90#comment-64769f68762228285567eb92)）
明示的に呼び出すまで処理を実行しないように一旦クラス化した。
Slack Appとしては開発していないのでそもそもプロジェクトを分ければよいが、今から移動するのは少し大変そう & 方針も曖昧なのでこちら側で対応する。
🔗  https://trello.com/c/9P3k440s
=> Refactor(attendance-manager): Freee clientをクラス化

hisyonosuke/src/app.ts, hisyonosuke/src/shift-changer/config.ts, hisyonosuke/src/shift-changer/shift-changer-api.ts, hisyonosuke/src/shift-changer/shift-changer.ts
シフト変更の操作をスプレッドシート上で行うようにした。
参考Trello (https://trello.com/c/9P3k440s)
=> スプレッドシート上でシフト変更の操作

hisyonosuke/jest.config.js, hisyonosuke/package.json, hisyonosuke/src/attendance-manager/action.ts, hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/freee.ts, hisyonosuke/src/attendance-manager/message.test.ts, hisyonosuke/src/attendance-manager/message.ts, hisyonosuke/src/attendance-manager/userWorkStatus.test.ts, hisyonosuke/src/attendance-manager/userWorkStatus.ts, hisyonosuke/src/attendance-manager/utilities.ts, yarn.lock
https://github.com/siiibo/hisyonosuke/pull/31 で休憩打刻機能を実装する際に行った休憩機能以外の変更を取り入れるためのPR
=> refactor(attendance-manager): jestの導入 & ts-pattern・neverthrowの活用

hisyonosuke/src/shift-changer/shift-changer.ts
Tech / Biz の情報の紐付けをslackのプロフィール → [アルバイトDB](https://docs.google.com/spreadsheets/d/1wad1H4i8h0VeijW75Wyu7VKrklvUyoYSmO6hOS3w-TE/edit#gid=0) で行うように変更した
[参考Trello](https://trello.com/c/TouSMz7X/458-tech-biz%E3%81%A8%E5%90%8D%E5%89%8D%E3%81%8C%E5%AF%BE%E5%BF%9C%E3%81%97%E3%81%AA%E3%81%84)
=> Tech / Biz 情報をemailから取得

.github/workflows/deploy.yml, hisyonosuke/README.md
今まで基本一人で開発していたので手動実行で誤魔化していたが、複数人で開発する際に不便なのでGHAで自動でプロイできるようにする。
大部分は https://github.com/siiibo/bank-holidays から拝借。
🔗 https://trello.com/c/bd0ZGNuj
=> ci(hisyonosuke): GHAで自動デプロイ

hisyonosuke/src/app.ts
app.tsにあった `ts-ignore` コメントを削除した。
https://github.com/siiibo/hisyonosuke/pull/16 でTypeScriptのstrictモードを有効化していたが、複数のプロジェクトを[エイヤで統合していた](https://trello.com/c/OsOtwbpt)影響でとりあえず `ts-ignore` を追加してエラーを無視していた。
https://github.com/siiibo/hisyonosuke/pull/59 でコードの大部分を削除したため、編集すべき部分が少なく済みそうだったので、 `ts-ignore` コメントを削除した上でエラーを解消した。
基本的に 「`undefined` になりうる値」が存在するエラーなので、 `undefined` のときの条件分岐を追加した。
=> refactor: remove ts-ignore comment

.github/workflows/deploy.yml
https://github.com/siiibo/hisyonosuke/pull/62 で https://github.com/daikikatsuragawa/clasp-action の利用をやめていたが、この内部で行われていた `.clasprc.json` と `.clasp.json` を追加し忘れていたため修正。
=> fix(gha): add clasp credential setting

attendance-manager/appsscript.json
https://github.com/siiibo/hisyonosuke/pull/61 でAddOnとWebAppの公開が不要になったので、appsscript.jsonからも関連設定を削除した。
=> chore: remove webapp & addon settings

attendance-aggregation/package.json, attendance-manager/package.json, pnpm-lock.yaml
=> chore: Update dependencies 202412 (#CIT-951)

attendance-aggregation/src/slack.ts, attendance-aggregation/tsconfig.json, attendance-manager/src/userWorkStatus.ts, attendance-manager/tsconfig.json, tsconfig.json
最新の[tsconfigの共通設定](https://www.notion.so/siiibo/tsconfig-aba1a40a91d5447b925d2a2de91bdb12)に合わせてtsconfigを更新
=> chore: tsconfigの最新化 (#CIT-951)
