siiibo/hisyonosuke

hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/freee.ts
https://github.com/siiibo/hisyonosuke/pull/6 の追加修正。
以下 https://github.com/siiibo/hisyonosuke/pull/6#issuecomment-1050674701 より転記。
https://developer.freee.co.jp/docs/hr/reference#/%E5%8B%A4%E6%80%A0/get_employee_work_record
```
"break_records": [
{
"clock_in_at": "2022-02-25T09:12:40.156Z",
"clock_out_at": "2022-02-25T09:12:40.156Z"
}
],
```
勤怠情報をgetしたときのbreak_recordsは↑の形式で来るので `yyyy-MM-dd HH:mm:ss` の形式にformatする必要があった。
（[退勤打刻時](https://siiibo.slack.com/archives/C018XK4E9CG/p1645780102630649?thread_ts=1645746618.487839&cid=C018XK4E9CG
)に発覚。APIを直接叩いてテストしたときはformatされた値を利用していた）
=> [fix] format break_records

hisyonosuke/src/attendance-manager/attendanceManager.ts
「Slackで出勤打刻忘れ → freeeで出勤打刻  → Slackで退勤打刻」
↑のように打刻を行うと、リモートメモが追加されてしまうバグの修正
=> [fix] 「freeeで出勤打刻→Slackで退勤打刻」を行うとリモートメモが追加されるバグの修正

hisyonosuke/src/attendance-manager/attendanceManager.ts
前日の退勤を忘れて出勤打刻を行うと「打刻の日付が不正な値です」というエラーが返される([例](https://siiibo.slack.com/archives/CL0V50APP/p1652394316230099?thread_ts=1652394146.912299&cid=CL0V50APP))ようなので、わかりやすいようにフィードバックメッセージを追加。
=> [feature] 前日の退勤忘れを出勤打刻時エラーに追加

hisyonosuke/src/attendance-manager/attendanceManager.ts
https://siiibo.slack.com/archives/CL0V50APP/p1655824357486319 のように、0:00以降に退勤した際にリモートメモを登録する処理でエラーが発生していたため修正。
=> Fix: 1日リモート勤務 & 0:00以降に退勤すると発生するバグの修正

hisyonosuke/src/attendance-manager/attendanceManager.ts
既存の実装では5分毎の処理について、最初の段階で既に処理されたメッセージ（打刻完了のフィードバック付きコマンド）から各ユーザーの勤務状態を計算し、勤務状態と最新の入力コマンドから後続の処理を決定している。
そのため、5分以内に同一ユーザーから複数コマンドがあった場合に対応できていない。
↑に対応するには勤務状態の更新処理をコマンドの処理毎に入れ込む必要がある
=> Fix: 5分以内に複数コマンドがあった場合に正しく処理できるようにする

hisyonosuke/src/attendance-manager/freee.schema.ts
勤怠メモ登録時にZodのparse Errorが発生していたため修正。
🔗  https://trello.com/c/DUHEpL2J
---
[この退勤コマンド](https://siiibo.slack.com/archives/C018XK4E9CG/p1679018585520999?thread_ts=1679018373.690159&cid=C018XK4E9CG)にて発生。
エラーは以下の通り
```
[
{
"code": "invalid_type",
"expected": "number",
"received": "undefined",
"path": [
"total_latenight_overtime_except_normal_work_min"
],
"message": "Required"
}
]
```
=> [attendance-manager] Fix: freee API Schemaの修正

hisyonosuke/package.json, hisyonosuke/src/attendance-manager/message.ts, yarn.lock
https://siiibo.slack.com/archives/C03R8GYG56C/p1680485834775589 より
3/13まではリモート → 出社切替時の通勤費判定が正常に動いているが、3/15以降出社に切り替えても退勤時にリモートメモが追加されてしまっているので修正する
🔗 https://trello.com/c/qARCn6MG
=> [attendance-manager] Fix: リモート → 出社に切り替えた際の通勤費判定を修正

.gitignore, hisyonosuke/package.json, hisyonosuke/src/attendance-manager/attendanceManager.ts, hisyonosuke/src/attendance-manager/auth.ts, hisyonosuke/src/attendance-manager/config.ts, yarn.lock
秘書之介に変更を入れる際、Productionコードに開発中のコードを適用してまうとバグが発生した場合に打刻ができなくなってしまって不便なので、開発用のSlack Appを導入する
休憩打刻追加ようのブランチで作業していたが、差分が大きくなりそうだったので先にこちらを導入
- production, developmentでGASプロジェクトそのものを分ける
- それぞれでproduction用, development用のWeb App URLを発行する
- development用のSlack Appも追加し、それぞれに対応するURLを割り当てる
:link: https://trello.com/c/DUHEpL2J
=> [Hisyonosuke] Chore: development環境の追加

hisyonosuke/src/attendance-manager/freee.ts
リモート出勤した日の退勤時、`リモート` メモを書き込むタイミングでちょいちょい以下のエラー発生しており、毎回修正依頼投げる必要がある。
入力自体は正しい（意図的にエラーを吐くべきタイミングではない）ので、リトライ処理入れて対応頻度を減らす。
> `"status_code":500,"errors":[{"type":"internal_server_error","messages":["エラーが発生しました。再試行しても解消しない場合は、サポートセンターまでご連絡ください。"]`
🔗 https://trello.com/c/FNbBivu2
=> [attendance-manager] Feature: 勤怠登録のエラー発生時にリトライ処理を入れる

hisyonosuke/package.json, hisyonosuke/src/attendance-manager/freee.ts
Dev環境でcreateFetchが呼び出されるとfreeeのtokenがexpiredでエラーとなるので、環境変数で切り分ける
https://github.com/siiibo/hisyonosuke/pull/30 関連
:link: https://trello.com/c/fWr8KHHN
=> Feature(attendance-manager): fetch関数の挙動をenvで切り分け

hisyonosuke/src/part-timer-shift/notify.ts
参考Trello (https://trello.com/c/pFtALH9s)
パートタイマーシフトの通知を営業日以外に行うのをやめる。
=> 営業日以外の通知をなくす

hisyonosuke/src/app.ts
絵文字作成時のwebhookを起点に雑談chに絵文字作成通知を流すプログラムを削除する。
GASで動かした本ツールではSlackの3秒ルールを守れずにリトライ処理が多発していたため、Slackの新プラットフォーム（Deno App）を使った方法に切り替える。
移行先のRepository → https://github.com/siiibo/slack-emoji-manager
🔗 https://trello.com/c/sYefsndQ
=> feat: 絵文字通知関連のコード削除

hisyonosuke/src/shift-changer/config.ts, hisyonosuke/src/shift-changer/shift-changer.ts
シフトの操作があった際、業務に関わってる社員にもメンションが飛ぶようにした
アルバイトDB (https://docs.google.com/spreadsheets/d/1wad1H4i8h0VeijW75Wyu7VKrklvUyoYSmO6hOS3w-TE/edit#gid=0) のD列から取ってくる。複数社員含む場合は カンマ区切り、半角空白。
[trello](https://trello.com/c/zAKcEMgk)
=> 社員メンションの追加

hisyonosuke/src/shift-changer/shift-changer.ts
replaceAllに正規表現を利用した際、実行時に以下のエラーが出てしまった。
```
TypeError: String.prototype.replaceAll called with a non-global RegExp argument
```
グローバルな正規表現を利用してなかったことが原因だったので、修正した。
=> 社員メンション追加時のバグ修正

.github/workflows/deploy.yml
GHAのpathsとpaths-ignoreは一緒に使えないらしいので、pathsに統合する
🔗 https://trello.com/c/bd0ZGNuj
=> fix(ci): paths-ignoreをpathsに統合

.github/workflows/deploy.yml
https://github.com/siiibo/hisyonosuke/pull/46 でpaths-ignoreをpathsに統合したが、hisyonosukeディレクトリの指定のみだとGHAを更新した際にGHAがトリガーされないので .github/を追加する
🔗 https://trello.com/c/bd0ZGNuj
=> ci(hisyonosuke): pathsに.githubの追加 & 末尾に/**の追加

.github/workflows/deploy.yml
clasp deployに渡すdescriptionをgithub.shaに変更する。
https://github.com/siiibo/hisyonosuke/pull/45#discussion_r1275887852 にある通り、clasp deployするために利用しているGHAの https://github.com/daikikatsuragawa/clasp-action ではdescriptionの変数がquoteされておらず、commit messageが空白や特殊文字を境目に途切れてしまう問題があるため。
🔗 https://trello.com/c/bd0ZGNuj
=> ci(hisyonosuke): use sha for GAS deployment description

hisyonosuke/src/shift-changer/shift-changer.ts
勤務場所が空でも、そのまま予定が登録されてしまう。そのため、勤務場所が空の場合はエラーを飛ばすようにした。
[参考Trello](https://trello.com/c/jjyI9fg3)
=> 勤務場所が空にならないようにする

hisyonosuke/src/shift-changer/shift-changer.ts
シフト変更用の名前をslackのプロフィールから取得していたが、アルバイトDBからemailと付き合わせることで取得する方式に変更した。
[参考Trello](https://trello.com/c/TG2jdXH5)
=> シフト変更通知用の名前をアルバイトDBから取得する

hisyonosuke/src/shift-changer/shift-changer.ts
シフト提出時に “The email is not in the slack members” エラーが出てしまう。
managerEmail欄が空文字だと、slackMemberからメンバーを見つけられない → エラーを吐く という流れ。
managerEmailが空文字の場合は、managerEmailsを空配列にすることで、slackId取得時のエラーを吐かないようにした。
[参考Trello](https://trello.com/c/cwMWAf77)
=> The email is not in the slack members エラーの解消

hisyonosuke/src/shift-changer/shift-changer.ts
シフト変更ツールのシフト変更 / 削除で「予定の表示」をクリックすると、「範囲の行数には 1 以上を指定してください。」エラーが出てしまう。
これは、予定を表示する際にシートの値をクリアするが (すでに予定を表示している場合、そのまま上書きするのを避けるため) 、シートの値が元からないときに`getRange`で取得する行数が0行となるためエラーが出ている。
[参考Trello](https://trello.com/c/DwaYJEZF)
=> 「範囲の行数には 1 以上を指定してください。」エラーの解消

hisyonosuke/src/shift-changer/shift-changer.ts
[参考Trello](https://trello.com/c/Gc7y910C)
利用者が予定を表示するとき日付の指定を忘れると、`noEvents` エラーが出てしまう。
以下の変更を加えた。
- 日付が空の場合は`specify date` エラーを出す
- シート挿入時に、デフォルトで今日の日付をセットする
- 日付指定のセルも色付きにする
=> fix: 予定表示で日付を指定しない場合に発生するnoEventsエラーの解消

hisyonosuke/src/shift-changer/shift-changer.ts
予定に共通な項目 `Type` `Who` を最初にまとめて表示するようにした。また、名前はフルネームではなく名字のみにした。
また、`変更` の際は変更前と後の予定を縦に並べ、 予定の間に区切り `---` を入れた。
以下が出力例。
`登録`
```
Biz戸倉さんの以下の予定が追加されました。
【リモート】 07/25 12:00~17:00 (休憩: 14:00-15:00)
【リモート】 07/27 13:00~16:00
```
`削除`
```
Biz戸倉さんの以下の予定が削除されました。
【リモート】 07/25 12:00~17:00
【リモート】 07/27 13:00~16:00
```
`変更`
```
Tech大類さんの以下の予定が変更されました。
---
【リモート】 07/25 09:00~12:00
↓
【リモート】 07/24 13:00~16:00 //←差分を太字にする
---
【出社】 07/28 10:00~14:00
↓
【出社】 07/28 13:00~17:00  (休憩: 14:00-15:00)
```
[参考Trello](https://trello.com/c/RGu7tinA)
=> 通知のフォーマットを変更する

hisyonosuke/src/shift-changer/shift-changer.ts
今までのシフト変更ツールでは、変更・削除シートで変更情報と削除情報を記入し提出すると、変更 / 削除で分かれて2回投稿が行われる。
2回連続で投稿することで、2回目の投稿時にslackの429エラーが出て投稿できないことがあったので、一度にまとめて投稿したい。
[参考Trello](https://trello.com/c/rQVRkPlw)
=> modificationMessageとdeletionMessageをまとめて通知

.github/workflows/deploy.yml, attendance-manager/package.json
https://github.com/siiibo/hisyonosuke/pull/61 でGASをWeb Appとしてdeployする必要がなくなったので、clasp deployが絡むGHAのコードを削除し、buildpushのみ実行するよう変更した。
=> chore: remove gha for deployment

.github/workflows/deploy.yml
https://github.com/siiibo/hisyonosuke/pull/62 行ったGHAの変更にてyarn workspaceの指定まで削除してしまったため修正。
=> fix: add yarn workspace

.devcontainer/devcontainer.json
このPRは、docker環境設定ファイルのエラーを解消しました。
少し前、absent-announce-botでも同じようなことが起こった。→https://github.com/siiibo/absent-announce-bot/pull/16
dockerの環境構築をする際に"fish": "latest"でレガシ機能はサポートされていません。というエラーが出てしまっていた。
その箇所の参照パスを変更することにより環境構築することができた。
変更前:`"fish": "latest"`→変更後:`"ghcr.io/meaningful-ooo/devcontainer-features/fish": "latest"`
[関連Notion](https://www.notion.so/siiibo/hisyonosuke-fish-75f3c6d2693c4438b9d53ee8379a42b9?pvs=4)
=> chore: devcontainer環境構築ファイルのfishの参照パスの変更

attendance-manager/src/attendanceManager.ts
#67 で本番環境で実験をした際にエラーが出てしまったそれを解決することを目的とする。
主要変更
- `setTimeClocks`に渡す引数の`base_date`が当日になってしまっていたため、前日の日付に変更。
日付を跨いだ時の退勤は前日の日付が必須であるため:[ドキュメント](https://developer.freee.co.jp/reference/hr/reference#operations-tag-タイムレコーダー(打刻))
その他変更・追加内容
- 自動退勤された人のログを表示できるようにログを追加
- Result型を用いて例外処理を書くように変更
[関連Notion](https://www.notion.so/siiibo/30aca1d9edfc4b368b81f88d6cfb62c5?pvs=4)
=> fix: 自動退勤システムのエラー解決

attendance-manager/src/attendanceManager.ts
このPRは、自動退勤システムの退勤時間の変更を行ったものである。
現状、実行した時間に退勤が押される仕組みになっている。
しかし、労働時間などの観点より出勤時間+9時間が適しているため変更を加えた。
変更内容
- 出勤時間に9時間を加えた時間を退勤時間にするように変更。
FreeeAPIの勤怠取得を用いて出勤時間を取得:[APIリファレンス](https://developer.freee.co.jp/reference/hr/reference#operations-tag-勤怠)
[関連Notion](https://www.notion.so/siiibo/20f91f007d514e8db6187ae4d8287bf3?pvs=4)
=> feat: 自動退勤する際の退勤時間を変更

attendance-manager/src/freee.schema.ts
[【freee人事労務】API仕様の変更について（勤怠API、勤怠情報サマリAPI）](https://developer.freee.co.jp/news/6774/)でアナウンスのあった変更に破壊的変更が含まれており、2024年2月上旬に`normal_work_mins_by_paid_holiday`プロパティが廃止される旨が記載されていた。
attendance-managerではこのプロパティを利用していないが、zodのSchema定義ではrequiredとしており、`handleClockOutAndAddRemoteMemo`関数内で`freee.getWorkRecord` を呼び出す際にparseエラー（requiredと定義されているプロパティにundefinedが渡ってきている）が発生していたため、`normal_work_mins_by_paid_holiday`プロパティを削除した。
=> fix: 廃止になったnormal_work_mins_by_paid_holidayプロパティの削除 (#CIT-599)

attendance-manager/src/attendanceManager.ts
リモートの人が自動退勤システムで退勤が押された場合、freeeのメモに`リモート`と自動で記述されるような機能を追加した。
変更詳細(変更ありマージ前に変更する)
- ローカル型としてfreeeに渡すパラメータの型を作成した
- userStatusからリモート出勤なのかを判定しnoteに追加するように変更
=> feat: 自動退勤システムのリモートの際にメモを記入する機能を追加する (#CIT-597) 

attendance-manager/src/attendanceManager.ts
自動退勤後に変更したのかがわかりやすいようにのslackのコメントを追加し、修正後に必ずスタンプを押してもらうようにする。
変更内容
- slackのコメントに「修正したら :done: スタンプを押してください。」を追加した
=> feat: 自動退勤システムのslackコメントに修正後にスタンプを押すように指示を追加する (#CIT-604)

attendance-manager/src/attendanceManager.ts, attendance-manager/src/userWorkStatus.ts
自動退勤システムの退勤時間を**slackのメッセージの出勤時間**+9時間にするように変更する。
#70 で実装していたが、FreeeのAPIで取得できる`clock_in_at`が退勤が押された場合に確定されるため、`clock_in_at`が見つからないとエラーが発生してしまっていた。
変更詳細
- UserWorkStatus型にclockInTimeを追加し出勤時間を取得できるようにした
- userWorkStatusesから出勤時間を取得し+9時間の時間で退勤を押すようにした
=> feat: 自動退勤に用いられる退勤時間をslackの出勤時間から計算するように変更する (#CIT-605)

attendance-manager/src/userWorkStatus.ts
自動退勤システムの出勤時間を取得する際のスタンプの条件を修正した。
修正前は、`出勤`スタンプのみの時間を取得し出勤時間を取得していた。しかし、勤務開始のスタンプは3種類あったので条件を変更し対応できるようにした。
変更詳細
- commandTypeの条件に`CLOCK_IN_AND_ALL_DAY_REMOTE_OR_SWITCH_TO_ALL_DAY_REMOTE`:リモートスタンプを追加
- commandTypeの条件に`CLOCK_IN_OR_SWITCH_TO_OFFICE`:出社スタンプを追加
___
勤務開始のスタンプの種類は3つある。
1. 出勤 → ただの出勤 : `CLOCK_IN`
2. 出社 → `リモート→出社`の勤務場所切り替えや`出勤`のどちらも使える: `CLOCK_IN_OR_SWITCH_TO_OFFICE`
3. リモート出勤 → リモート出勤 : `CLOCK_IN_AND_ALL_DAY_REMOTE_OR_SWITCH_TO_ALL_DAY_REMOTE`
=> fix: 自動退勤の出勤時間の取得の際のスタンプ条件を修正 (#CIT-616)

attendance-manager/src/attendanceManager.ts, attendance-manager/src/freee.schema.ts
Freee上で半休登録を行い、その後リモートで仕事を行い退勤を行った際に半休情報が消えてしまっていた。
リモート出勤で退勤を押すと、Freee上のメモを記述するために打刻を更新し登録を行っている。しかし、登録を更新する際に半休情報を切り捨てて更新を行ってしまっていた。
変更内容
- メモを登録するために用いていた`updateWorkRecord`に半休の時間を与えるように変更
- 半休の時間を取得するために`getWorkRecord`の型を変更
=> fix: updateWorkRecordを行う際に半休情報を含めて更新を行うようにする (#CIT-624)

attendance-manager/src/message.test.ts, attendance-manager/src/message.ts
https://siiibo.slack.com/archives/CL0V50APP/p1727740892476559?thread_ts=1727740806.556919&cid=CL0V50APP で発覚。
月跨ぎ & 深夜0:00を過ぎたタイミング（翌月初になったタイミング）で打刻すると打刻が機能しないバグを修正。
=> fix: 月末の深夜に退勤した場合に打刻が正常に完了しないバグの修正 (#CIT-964)

.vscode/settings.json, attendance-aggregation/package.json, attendance-manager/package.json
GitHub Actionsとdependabot導入に向けた前準備として、type-checkとlint用のnpm scriptsを追加した。
=> chore: chore: type-checkとlint用のnpm scriptsを追加 (#CIT-981)
